#Notable game designers
* Nolan Bushnell
* Sidney Meier
* Gabe Newell
* Will Wright
* Brenda Brathwaite
* Chris Crawford
* Ron Gilbert
* Todd Howard
* Ken Levine
* Cliff Bleszinski
* Hideo Kojima
* John Romero
